defaults:
  exp_name: ppo_thesis_exp
  seed: 0
  torch_deterministic: true
  cuda: true
  track: true
  wandb_project_name: "thesis-cleanrl"
  wandb_entity: 'fionalluo'
  capture_video: false

  task: CartPole-v1
  total_timesteps: 500000
  learning_rate: 2.5e-4
  num_envs: 4
  num_steps: 128
  anneal_lr: true
  gamma: 0.99
  gae_lambda: 0.95
  num_minibatches: 4
  update_epochs: 4
  norm_adv: true
  clip_coef: 0.2
  clip_vloss: true
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  target_kl: None
  full_keys: {mlp_keys: '.*', cnn_keys: '.*'}
  keys: {mlp_keys: '.*', cnn_keys: '.*'}
  # PPO Unified Network Architecture
  # CNN Encoder Architecture
  mlp_hidden_dim: 256
  mlp_output_dim: 512
  cnn_output_dim: 512
  latent_dim: 1024

  env:
    atari: {size: [64, 64], repeat: 4, sticky: True, gray: False, actions: all, lives: unused, noops: 0, resize: opencv}
    dmlab: {size: [64, 64], repeat: 4, episodic: True}
    minecraft: {size: [64, 64], break_speed: 100.0}
    dmc: {size: [64, 64], repeat: 2, camera: -1}
    loconav: {size: [64, 64], repeat: 2, camera: -1}
    gym: {obs_key: state}

# ====================
# Named Configs
# ====================

cartpole_small:
  task: CartPole-v1
  total_timesteps: 200000
  learning_rate: 1e-3
  num_envs: 2
  num_steps: 64

gymnasium_bandit5:
  task: gymnasium_BanditPathEnv5-v0
  total_timesteps: 50000
  num_envs: 4
  num_steps: 128
  full_keys: {mlp_keys: '\b(target|neighbors|distance|position)\b', cnn_keys: '^$'}
  keys: {mlp_keys: '\b(target_unprivileged|neighbors_unprivileged|position)\b', cnn_keys: '^$'}
  exp_name: "bandit5"

gymnasium_lavatrail8:
  task: gymnasium_LavaTrail8x8-v0
  total_timesteps: 50000
  num_envs: 4
  num_steps: 128
  full_keys: {mlp_keys: '\b(neighbors|last_action|grid|position)\b', cnn_keys: '^$'}
  keys: {mlp_keys: '\b(neighbors_unprivileged|last_action|grid_unprivileged|position)\b', cnn_keys: '^$'}
  exp_name: "lavatrail8"

gymnasium_blindpick:
  task: gymnasium_FOFixedGripper2DBlind7cmPick-v0
  total_timesteps: 50000
  num_envs: 4
  num_steps: 128
  full_keys: {mlp_keys: '.*', cnn_keys: '.*'}
  keys: {mlp_keys: '.*', cnn_keys: '^$'}
  exp_name: "blindpick"
